spring:
  application:
    name: expensetrackersvc
  datasource:
    url: jdbc:mysql://localhost:3306/expensetracker
    username: root
    password: tanv
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



server:
  servlet:
    context-path: /api/v1.0
